enabled: true
custom_logo:
  user/themes/greenspeed/images/logo/logo.png:
    name: logo.svg
    type: image/svg
    size: 5238
    path: user/themes/greenspeed/images/logo/logo.svg
footer-text: '© Copyright Greenspeed 2018'
footer-design: 'copyright'

footer-additional-text: 'further text'
