enabled: true
custom_logo:
  user/themes/greenspeed/images/logo/spiral-logo.png:
    name: spiral-logo.png
    type: image/png
    size: 5238
    path: user/themes/greenspeed/images/logo/spiral-logo.png
footer-text: '© Copyright Greenspeed 2019'
footer-design: 'copyright'

footer-additional-text: 'further text'
